name: Manual
on: 
  workflow_dispatch:                        # 手動イベント
    inputs:
      greeting:                             # 入力パラメータ名
        type: string                        # データ型 (文字列)
        default: Hello                      # 入力パラメータのデフォルト値
        required: true                      # 入力パラメータの必須フラグ
        description: A Cheerful word        # 入力パラメータの概要
jobs:                                       # definement job
  run:                                      # job id
    runs-on: ubuntu-latest                  # runner (Ubuntu)
    steps:                                  # definement steps
      - run: echo "${{ inputs.greeting }}"  # implement shell command